import { useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import { RantDisplay } from "~/components/RantDisplay";
import { RantForm } from "~/components/RantForm";
import { api } from "~/utils/api";

export default function Home() {
  const { user } = useUser();

  const { data, refetch } = api.rant.getAll.useQuery();

  const { mutate, isLoading } = api.rant.createRant.useMutation({
    onSuccess: async () => { await refetch() }
  });

  return (
    <>
      <Head>
        <title>Relieve Notes.</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="text-[hsl(280,100%,70%)]">Relieve</span> Notes.
          </h1>
          <h1 className="text-4xl text-slate-100">
            What you want to rant about {user?.fullName}?
          </h1>
          <RantForm onSubmit={mutate} isLoading={isLoading} />
          {data?.map((rant) => (
            <RantDisplay key={rant.id} rant={rant} />
          ))}
        </div>
      </main>
    </>
  );
}
